### PR TITLE
Pareto principle

### PR DESCRIPTION
**Pull request by rbalazs**
**Pull Request Checklist**

Please double check the items below!

- [x] I have read the [Contributor Guidelines](./.github/contributing.md).
- [x] I have not directly copied text from another location (unless explicitly indicated as a quote) or violated copyright.
- [x] I have linked to the original Law.
- [x] I have quote the law (if possible) and the author's name (if possible).
- [x] I am happy to have my changes merged, so that I appear as a contributor, but also the text altered if required to keep the language consistent in the project.

And don't forget:

- I can handle the table of contents, feel free to leave it out.
- Check to see if other laws should link back to the law you have added.
- Include your **Twitter Handle** if you want me to include you when tweeting this update!

### CODE REVIEW

**Comment by isu182** [comment]
:+1:

**Comment by dwmkerr** [comment]
Love it, thanks for sharing! Will merge a new law every few days or so to spread out the updates!

**Comment by hattila** [comment]
+1

**Comment by dwmkerr** [comment]
Awesome, thanks @rbalazs! I've merged, made a couple of minor edits (moving to the 'principles' section, adding a link to the microsoft example) and am ready to publish now! Do you want me to mention you on LinkedIn/Twitter? If so just let me know your handle or add me so I can mention you. If not that's fine I'll just comment it as an open source contributor. I'm at https://www.linkedin.com/in/dwmkerr/

**Comment by rbalazs** [comment]
Thanks @dwmkerr : ) It's fine, I am glad (and also proud) that I've could contribute. 

Thanks for the edits, and the merge, and congrat for the awsome project!

**Comment by dwmkerr** [comment]
Thanks @rbalazs!

**Pull request merged**
