### PR TITLE
Add Shirky Principle

### PR DESCRIPTION
**Pull request by BoltzmannBrain**

### CODE REVIEW

**Comment by dwmkerr** [comment]
Hi @BoltzmannBrain sorry for the slow response! The principle looks relevant, but I'm trying to think of a good example. The one in the source article was clearly disputed - do you have any good examples from tech to add to this?

**Comment by willsheldon** [comment]
For a suitable example, what about Microsoft paying the German government (Munich) to move back to windows from Linux: https://mspoweruser.com/german-government-switching-back-to-windows-os-from-linux-after-10-years/

**Comment by Joshfindit** [comment]
I feel like this is common among talks with companies who seem to be stuck in the “old way of doing things” when there are software tools readily available.

Examples: continual dependence on MS Excel and fax for “secure” communication (still prevalent in the medical sector)

**Comment by dwmkerr** [comment]
Great - thanks @Joshfindit @willsheldon  @BoltzmannBrain I'll merge, update the examples and publish this eve!

**Pull request merged**
