### PR TITLE
added "The Paradox of Choice".

### PR DESCRIPTION
**Pull request by ustundag**
**Pull Request Checklist**

Please double check the items below!

- [x] I have read the [Contributor Guidelines](https://github.com/dwmkerr/hacker-laws/blob/master/.github/contributing.md).
- [x] I have not directly copied text from another location (unless explicitly indicated as a quote) or violated copyright.
- [x] I have linked to the original Law.
- [x] I have quote the law (if possible) and the author's name (if possible).
- [x] I am happy to have my changes merged, so that I appear as a contributor, but also the text altered if required to keep the language consistent in the project.

And don't forget:

- I can handle the table of contents, feel free to leave it out.
- Check to see if other laws should link back to the law you have added.
- Include your **Twitter Handle** if you want me to include you when tweeting this update!

### CODE REVIEW

**Comment by ustundag** [comment]
closes #307

**Comment by ustundag** [comment]
Hi @dwmkerr , could you please review this PR? I'm really curious about your opinion. I think that most junior developers experience this paradox once their life.

**Comment by dwmkerr** [comment]
Hi @ustundag thanks for raising the PR! I'm in two minds about this one. The first reason is that the law is (at least in the book) focusing more on 'consumer decision making'; choosing options in a store, what film to see, etc etc. This is not necessarily a problem, we have other laws here from other domains, but I think the book has a focus on that _kind_ of choice.

The second concern I have is that suggesting that the anxiety around choosing a framework is a consequence of _The Paradox of Choice_ might be tenuous. Basically this is a _different_ kind of choice, not one of a consumer choosing what product their prefer, but essentially an architect choosing how to design something; a by definition highly consequential decision. In fact I think it could be argued that the _same_ anxiety would be felt if making a choice between a small set of options (e.g. "You can choose React or Angular for your front end, but whether the project succeeds or not will be the consequence of your decision). Here the anxiety comes not from the number of choices, but the _consequence_ of the decisions. In this case, this is anxiety around a 'type one' decision:

https://www.businessinsider.com/jeff-bezos-on-type-1-and-type-2-decisions-2016-4

Then there is _another_ element to this - the anxiety of any engineer with the overwhelming domain they have to know about. This is not necessarily a paradox of choice as much as an anxiety like "There is a _tonne_ of tech, more every day, how the hell can I be competent enough in this domain to be effective?"

It's a tough one. I think that the _breadth_ of tech and the options available can definitely lead to anxiety, although I've seen similar anxiety when options are highly limited.

Any thoughts on this? I don't think the addition is necessarily wrong, I just want to make sure it can be relevantly applied to tech. I think that it would be fair to say that if you give a junior techie the choice to design a system using _anything_ the space of solutions is intimidating in itself so there is validity to that. But I also hesitate that this might be just inadvertently promoting a specific book which in a sense has a truism for engineering which is "if you are responsible for a decision, that makes you anxious, and if there are lots of choices, that can make you exposed (e.g. why did you choose X not Y)"

**Comment by ustundag** [comment]
Hi @dwmkerr thanks for your time and detailed reply, well explained your thoughts.

Upon your first concern, yes, the theory is based on consumer decision making but I think, we as tech/software crafters are also customers of tech products, even if utilizing an open-source. That's why we still keep considering the product we chose and other alternatives.

About type-1 and type-2 decisions, do you think that type-1 decisions always apply to tech? Since softwares are also alive products, they need to change and adapt to the current time. as far as I understand, this theory is about type-2 decisions and about that increasing the number of choices can trigger overthinking and make you frustrated about what you chose.

For your second approach, what I meant by choice is not only about frameworks/languages but also software domains such as ui, frontend, backend, devops, mobile, cloud, ai, bigdata etc. The point I've just want to make is that most juniors/new starters don't tend to look at quantitative performance metrics on which framework/architecture is more eligible, since they are trying to find a way to be specialized in. That's why, they end up having anxiety during decision-making and drowning in several options. Also, overthinking about this process makes it harder to adapt to the development environment newly chosen. I think, the key factor to put yourself out of this situation is just to stick to the choice, learn fundamentals, and focus on quantitative metrics of your software system, not the alternatives.

A long time ago, options and resources were few but determination is easy. But now, options are numerous, starting is easy with numerous resources(especially social media and learning/certification platforms) but decision-making and sticking to one choice is so hard. 

I respect and understand your hesitations about promoting a book. But wish we could name this kind of cognitive bias and psychological impact.

**Comment by ustundag** [comment]
Hi @dwmkerr While thinking about this theory, something came to my mind. Can we associate this law with "[Fear of Missing Out](https://en.wikipedia.org/wiki/Fear_of_missing_out)"?

**Comment by alxgda** [comment]
Just my 2 cents, but I think that these are more related towards psychology than systems engineering. If we start adding these kinds of principles, we may end up with a repos of general bias and mental models like some others repos. Let's focus on the engineering part.

**Comment by dwmkerr** [comment]
I'm inclined to agree @alxgda I think for now I'll close this PR to try and keep the laws focused on things that are clearly connected to tech, but thanks everyone for the support, discussion and contributions!

**Pull request closed without merging**
