### PR TITLE
Add "Echo Chamber Effect"

### PR DESCRIPTION
**Pull request by ustundag**
**Pull Request Checklist**

Please double check the items below!

- [x] I have read the [Contributor Guidelines](https://github.com/dwmkerr/hacker-laws/blob/master/.github/contributing.md).
- [x] I have not directly copied text from another location (unless explicitly indicated as a quote) or violated copyright.
- [x] I have linked to the original Law.
- [x] I have quote the law (if possible) and the author's name (if possible).
- [x] I am happy to have my changes merged, so that I appear as a contributor, but also the text altered if required to keep the language consistent in the project.

And don't forget:

- I can handle the table of contents, feel free to leave it out.
- Check to see if other laws should link back to the law you have added.
- Include your **Twitter Handle** if you want me to include you when tweeting this update!

### CODE REVIEW

**Comment by ustundag** [comment]
closes #323

**Comment by ustundag** [comment]
Hi @dwmkerr  , what do you think about this effect? would you mind sharing your opinions?

**Comment by dwmkerr** [comment]
Hi @ustundag sorry for the delay! I've read through the contribution and reasoning and I'm not sure it's an entirely appropriate contribution. Typically when people talk about the echo chamber effect they are referring to things like social media bubbles, feedback loops for online news, etc etc, and I'm not sure it has an immediately applicability to reasoning about software engineering. If we include it, we kind of open the door to almost any social/group effects, and that list will be _huge_ and much of it not software or technology related, what do you think?

**Comment by ustundag** [comment]
Hi, no problem. I understand the concern and you may be right with that. But I thought that this effect may belong to the same category where The Broken Windows Theory or The Dunning-Kruger Effect involved in. They are also even relevant to social effects. Interactions and communications with people are so essential and inevitable ways to improve, collaborate, etc. for us as developers thats why I think The Echo Chamber has also a huge impact on us.

**Comment by alxgda** [comment]
I agree with @dwmkerr. Let's avoid putting every existing mental bias on this repo. We should focus on engineering and systems.

**Comment by ustundag** [comment]
Thanks for your review and comments. I'll close it.

**Pull request closed without merging**
