### PR TITLE
Added Wheaton's Law

### PR DESCRIPTION
**Pull request by MrRyansan**
Added Wheaton's Law as I have found it to be SO useful in my development career. I learned how important it is to not be one, because nobody wants to work with one.

**Pull Request Checklist**

Please double check the items below!

- [x] I have read the [Contributor Guidelines](./.github/contributing.md).
- [x] I have not directly copied text from another location (unless explicitly indicated as a quote) or violated copyright.
- [x] I have linked to the original Law.
- [x] I have quote the law (if possible) and the author's name (if possible).
- [x] I am happy to have my changes merged, so that I appear as a contributor, but also the text altered if required to keep the language consistent in the project.

And don't forget:

- I can handle the table of contents, feel free to leave it out.
I added it, but feel free to adjust or change.

- Check to see if other laws should link back to the law you have added.
Didn't see any applicable, but please feel free to link to any I may have missed.

- Include your **Twitter Handle** if you want me to include you when tweeting this update!
No Twitter handle, so we're good there.

### CODE REVIEW

**Comment by fent** [comment]
> I learned how important it is to not be one, because nobody wants to work with one.

so were you going around being a dick to your coworkers til someone told you about this law? 😆 

and I think this repo is more for development related laws and less about a code of conduct in development

**Comment by siriak** [comment]
@fent, totally agree with you, this is not a law in a scientific sense at all because we can't make predictions based on it.

**Comment by MrRyansan** [comment]
> > I learned how important it is to not be one, because nobody wants to work with one.
> 
> so were you going around being a dick to your coworkers til someone told you about this law? 😆
> 
> and I think this repo is more for development related laws and less about a code of conduct in development

LOL, no... at least I hope I'm not perceived that way! And no worries if this gets scratched from the merge... I did notice that the PR guidelines did state these two things which I felt did apply:

- It is fine to include laws which are humorous or not serious.
- If a law does not obviously apply to development or coding, include a paragraph explaining the relevance to technologists.

And although it is somewhat humorous, I do think it is very applicable 🙂

But no hard feelings if the consensus is a no go for it. Thanks for at least considering it.

**Comment by siriak** [comment]
@MrRyansan sure, PR is fully compliant with guidelines, it's just my personal opinion. Of course, the final decision is after the repository maintainer :)

**Comment by dwmkerr** [comment]
Hi everyone - thanks for sharing @MrRyansan! I think that it is a good addition to the series, the rules don't have to be serious as you noted from the PR guidelines, and without wanting to stereotype there are plenty of techies who could do with remembering this (even some of the most famous ones like Linus Torvalds). So I think it's a good addition :)

I'll merge it during the week, and share on social media at the same time!

**Comment by dwmkerr** [comment]
Just another comment on this one, given humorous or slightly irreverent laws like:

- https://github.com/dwmkerr/hacker-laws#the-dilbert-principle
- https://github.com/dwmkerr/hacker-laws#putts-law
- https://github.com/dwmkerr/hacker-laws#murphys-law--sods-law

I think there's a fair number of laws which already fall into this category so it's a good one to add! But I appreciate the discussion on this and the attention people have given to make sure we don't de-value the content.

**Pull request merged**
