### PR TITLE
Linus's Law

### PR DESCRIPTION
**Pull request by umutphp**
Closes #167 

**Pull Request Checklist**

Please double check the items below!

- [+] I have read the [Contributor Guidelines](./.github/contributing.md).
- [+] I have not directly copied text from another location (unless explicitly indicated as a quote) or violated copyright.
- [+] I have linked to the original Law.
- [+] I have quote the law (if possible) and the author's name (if possible).
- [+] I am happy to have my changes merged, so that I appear as a contributor, but also the text altered if required to keep the language consistent in the project.

And don't forget:

- I can handle the table of contents, feel free to leave it out.
- Check to see if other laws should link back to the law you have added.
- Include your **Twitter Handle** if you want me to include you when tweeting this update!

### CODE REVIEW

**Comment by dwmkerr** [comment]
Hi @umutphp at the moment the first two paragraphs are a direct replication of the wikipedia article, so would violate their terms by not being attributed; are you able to reword so that the gist is still there but it is essentially original material (minus the quotes?) The last part is fine but the first is too close to the original wiki entry to not require attribution I think

**Comment by umutphp** [comment]
Hi @dwmkerr,

Thanks for the feedback :). I will update accordingly.

**Comment by dwmkerr** [comment]
No worries!

**Comment by dwmkerr** [comment]
Whoops haven't merged this yet, will do so today and publicise this eve! 

Might also recommend this on the reading list:

https://en.wikipedia.org/wiki/The_Cathedral_and_the_Bazaar

**Pull request merged**
