### PR TITLE
Some typos and added link to russian version.

### PR DESCRIPTION
**Pull request by pavelpy**
**Pull Request Checklist**

Please double check the items below!

- [*] I have read the [Contributor Guidelines](./.github/contributing.md).
- [*] I have not directly copied text from another location (unless explicitly indicated as a quote) or violated copyright.
- [*] I have linked to the original Law.
- [*] I have quote the law (if possible) and the author's name (if possible).
- [*] I am happy to have my changes merged, so that I appear as a contributor, but also the text altered if required to keep the language consistent in the project.

And don't forget:

- I can handle the table of contents, feel free to leave it out.
- Check to see if other laws should link back to the law you have added.
- Include your **Twitter Handle** if you want me to include you when tweeting this update!

### CODE REVIEW

**Comment by solarrust** [comment]
Hi @pavelpy ! I already translate this awesome digest to Russian =) 
https://github.com/solarrust/hacker-laws

**Comment by dwmkerr** [comment]
This is excellent, thanks @pavelpy ! Is there any chance you can fix the conflict, but also for the link to the Russian version also include the words in Russian (a bit like has been done with Chinese and Korean), so that any Russian readers who don't read English can still easily see the text?

I.e. it'd be something like:

```
🇷🇺 [русский / Russian Version](https://github.com/pavelpy/hacker-laws-ru) - thanks [Pavel K](https://github.com/pavelpy)!
```

The problem is I don't know if "русский" is Russian as in the language, or Russian as in the nationality, or even just a mistake from google translate!

BTW if you have a twitter handle/linkedin profile and want me to mention you in the update when I share it to give props, just let me know them!

**Comment by dwmkerr** [comment]
https://github.com/serega404/hacker-laws-ru @serega404 any thoughts on how to combine forces here?

**Comment by dwmkerr** [comment]
BTW am thinking of using GitLocalise to deal with this, WDYT?

https://gitlocalize.com/

**Comment by serega404** [comment]
I first learned about GitLocalise. But I will be happy to help with the
translation.

вт, 4 июн. 2019 г., 18:42 Dave Kerr <notifications@github.com>:

**Pull request closed without merging**
