### PR TITLE
Dunning-Kruger Effect

### PR DESCRIPTION
**Pull request by akashchandwani**
Resolves dwmkerr/hacker-laws#300

**Pull Request Checklist**

Please double check the items below!

- [x] I have read the [Contributor Guidelines](https://github.com/dwmkerr/hacker-laws/blob/master/.github/contributing.md).
- [x] I have not directly copied text from another location (unless explicitly indicated as a quote) or violated copyright.
- [x] I have linked to the original Law. 
- [x] I have quote the law (if possible) and the author's name (if possible).
- [x] I am happy to have my changes merged, so that I appear as a contributor, but also the text altered if required to keep the language consistent in the project.

And don't forget:

- I can handle the table of contents, feel free to leave it out.
- Check to see if other laws should link back to the law you have added.
- Include your **Twitter Handle** if you want me to include you when tweeting this update!

### CODE REVIEW

**Comment by dwmkerr** [comment]
Thanks @akashchandwani! I'm going to merge now - I'll probably tweak the text and example a bit, then will publicise when it's done! Appreciate the contribution :smile:

**Comment by dwmkerr** [comment]
Hi @akashchandwani just a heads up that I've merged, but also quite heavily changed this (this is why I held off on this one), I'm fairly familiar with the effect and it is really complex (it's also been challenged a number of times with other studies). In short:

- I've removed the quote, as it was a direct copy from wikipedia and didn't attribute it, _but_ replaced it with a quote from Dunning which describes the effect in shroit
- Added a specific real world example which I think is quite good (there's a link in the new text)
- Removed the image as I wasn't sure about copyright

This one is a really tough one because I think it requires quite a lot of explanation to describe that it is actually quite subtle and specific in its meaning, and is often over-used to suggest that "People who think complex things are simple give unreliable opinions on these things" which is more like a truism!

Anyway, hope the updated text is too your liking and thanks for contributing!

**Comment by akashchandwani** [comment]
Hi @dwmkerr, thanks for editing the content, I can agree no less by saying that the content looks much better and is easier to read now.

Just a note on the image (src: https://en.m.wikipedia.org/wiki/File:Dunning%E2%80%93Kruger_Effect_01.svg), The image is under the `Creative Commons CC0 1.0 Universal Public Domain Dedication`, that means it could have been used without any copyright infringement.  

Screenshot 2020-12-03 at 10 10 46 PM

I personally feel that the image provided was quite funny as well as quite elaborate in expressing the training part in the Dunning Kruger effect quite effectively. 

Also, regarding the content earlier, I wanted not to deviate much from the source of Dunning Kruger effect in the first stanza as it was quite well explained in wikipedia, thus the quote.. However, I do very well appreciate your edits :)

**Comment by dwmkerr** [comment]
ah thanks I hadn't realised the image was CC, appreciate the update!

**Pull request merged**
