### PR TITLE
Vietnamese

### PR DESCRIPTION
**Pull request by dungpt3003**
**Pull Request Checklist**

Please double check the items below!

- [ ] I have read the [Contributor Guidelines](./.github/contributing.md).
- [ ] I have not directly copied text from another location (unless explicitly indicated as a quote) or violated copyright.
- [ ] I have linked to the original Law.
- [ ] I have quote the law (if possible) and the author's name (if possible).
- [ ] I am happy to have my changes merged, so that I appear as a contributor, but also the text altered if required to keep the language consistent in the project.

And don't forget:

- I can handle the table of contents, feel free to leave it out.
- Check to see if other laws should link back to the law you have added.
- Include your **Twitter Handle** if you want me to include you when tweeting this update!

### CODE REVIEW

**Comment by dungpt3003** [comment]
We are working on it. We will open the pull request later.

**Comment by dwmkerr** [comment]
@dungpt3003 - if you log into GitLocalize and let me know your username I can make you the admin for the Vietnamese language if that helps!

**Comment by dungpt3003** [comment]
Hi @dwmkerr, thanks for you response, my GitLocalize username is **dungpt3003**. Currently, we are translating your content directly to the [README](https://github.com/dungpt3003/hacker-laws-vn/blob/master/README.md) file of our repository. We will open a pull request to yours when it is done.

**Comment by dwmkerr** [comment]
Done, thanks so much!

image

**Pull request closed without merging**
