### PR TITLE
Add The Dilbert Principle and The Peter Principle

### PR DESCRIPTION
**Pull request by markiv**

### CODE REVIEW

**Comment by dwmkerr** [comment]
Looks ace - can you check the new guidelines here (sorry just added them, mostly to make sure there's no inadvertent copyright violation) and then I can go ahead and merge them? I can handle the update to the TOC if that makes things easier as well 👍 

https://github.com/dwmkerr/hacker-laws/blob/master/.github/contributing.md
https://github.com/dwmkerr/hacker-laws/blob/master/.github/pull_request_template.md

**Comment by markiv** [comment]
Checked the guidelines. I believe we're good to go. Cheers! 👍

**Comment by cristaloleg** [comment]
Kindly ping 😉

**Comment by dwmkerr** [comment]
Cheers @cristaloleg reviewing now and will merge ASAP!

**Comment by dwmkerr** [comment]
Thanks @markiv! I'm merging now, will update the TOC, make sure the ordering is correct, then publicise tomorrow. I've sent an invite on LinkedIn and found your twitter profile, so will also link to you when I should out the update there!

**Pull request merged**
