### PR TITLE
add jp translation

### PR DESCRIPTION
**Pull request by freddiefujiwara**
**Pull Request Checklist**

Please double check the items below!

- [ ✓] I have read the [Contributor Guidelines](https://github.com/dwmkerr/hacker-laws/blob/master/.github/contributing.md).
- [✓ ] I have not directly copied text from another location (unless explicitly indicated as a quote) or violated copyright.
- [✓ ] I have linked to the original Law.
- [✓ ] I have quote the law (if possible) and the author's name (if possible).
- [✓ ] I am happy to have my changes merged, so that I appear as a contributor, but also the text altered if required to keep the language consistent in the project.

And don't forget:

- I can handle the table of contents, feel free to leave it out.
- Check to see if other laws should link back to the law you have added.
- Include your **Twitter Handle** if you want me to include you when tweeting this update!

### CODE REVIEW

**Comment by dwmkerr** [comment]
Looks excellent! @freddiefujiwara can you sign on to 'GitLocalise' and let me know when done? Then I can make you the moderator of the `jp` language and list you in the moderators below 😄  Thanks!

**Comment by freddiefujiwara** [comment]
@dwmkerr  thanks I've just sign in
image

**Comment by dwmkerr** [comment]
I'm checking with the GitLocalise team now and will let you know when solved, looks like it is broken for me at the moment too, cannot add another language - will update when fixed!

**Comment by freddiefujiwara** [comment]
@dwmkerr All right.
I'm waiting for information.

**Comment by dwmkerr** [comment]
OK it's fixed! You are the moderator for the `jp` language now, thanks for all your help!

**Pull request merged**
