### PR TITLE
Add Hutber's Law

### PR DESCRIPTION
**Pull request by rrix**
**Pull Request Checklist**

- [x] I have read the [Contributor Guidelines](./.github/contributing.md).
- [x] I have not directly copied text from another location (unless explicitly indicated as a quote) or violated copyright.
- [x] I have linked to the original Law.
- [x] I have quote the law (if possible) and the author's name (if possible).
- [x] I am happy to have my changes merged, so that I appear as a contributor, but also the text altered if required to keep the language consistent in the project.

It's an awfully cynical one, but it's a failure I've seen in the wild more times than I'd like to count.

### CODE REVIEW

**Comment by guicho271828** [comment]
not just cynical, but also grounded by no-free-lunch theorem.

**Comment by dwmkerr** [comment]
Cynical is fine, there's a bunch of those 👍 Especially when you combine some of them together! Just to double check, can you check the new contributors guidelines (mostly around copyright) before I merge?

**Comment by rrix** [comment]
Hey there, I updated the PR description and removed the ToC entry. Thanks :)

**Comment by dwmkerr** [comment]
Finally merged, thanks @rrix!

**Pull request merged**
