### PR TITLE
Explain "The Spotify Model"

### PR DESCRIPTION
**Pull request by aes**
Additional explanation (from someone who should know)

### CODE REVIEW

**Comment by aes** [comment]
Help rewording this is of course welcome!

> been a form of experiment

This is sort of wrong, it's *explicitly* the subject to experimentation, and that's the point. "The Spotify Model", as popularized, is/are basically random snapshots of a process in motion. Because that idea is so completely alien, people are unable to hear that it's intentionally a living process, and what they hear instead are the comfortably less alien details of the org at the snapshot time.

I don't really know how to phrase this to communicate it clearly and succinctly to someone not already on board with it. (as evidenced by this miscommunication, if nothing else.) (Plz Halp!)

**Comment by dwmkerr** [comment]
Thanks for the feedback! I want to get this right; getting feedback from someone who knows the topic first hand makes the content _vastly_ more valuable! It sounds like the mistake with the previous cut was that it suggested it was _initially_ experimentation, rather than is a deliberate and on-going experiment, is that right? If so:

What about this for the change:

> The Spotify Model also popularises the concepts of Tribes, Guilds, Chapters, which are other components of their organisation structure.
> 
> Members of the organisation have described that the actual meaning of these groups changes, evolves and is an on-going experiment. The fact that the model is a _process in motion_, rather than continues to lead to varying interpretations of the structure, which may be based on presentations given by employees at conferences. This means 'snapshots' may be 're-packaged' by third parties as a _fixed structure_, with the fact that the model is dynamic being lost.
> 
> This situation is so persistent, no matter what effort is expended to explain, that both meanings must be understood and accepted as the meaning of the phrase.

Given you have first hand experience, do you mind if I link a thanks to your github handle as a bullet or something under the notes? It accounts for the additional detail and also gives the perspective more credibility and context. Thanks!

**Comment by aes** [comment]
What is the status of this?

**Comment by dwmkerr** [comment]
Sorry, lost track of this, what do you think of my most recent comment on the rewording?

**Comment by aes** [comment]
Sure, that works. I'd prefer to not be called out in the text. If anyone cares, I can be found by looking at the project history, right?

**Comment by dwmkerr** [comment]
No worries! Done :smile:

**Pull request closed without merging**
